In [7]:
import numpy as np
import pandas as pd
import datetime
from keras.models import Sequential
from keras.layers import Dense, Dropout, BatchNormalization, Activation
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.utils import class_weight
import tf2onnx
import onnx
import pickle
from pathlib import Path

scaler = StandardScaler()
data = np.array([[0, 0, 0], [1, 0, 1], [0, 1, 2], [1, 1, 1]])

data = scaler.fit_transform(data)
print(data)
print(scaler.scale_, scaler.mean_, scaler.var_)

[[-1.         -1.         -1.41421356]
 [ 1.         -1.          0.        ]
 [-1.          1.          1.41421356]
 [ 1.          1.          0.        ]]
[0.5        0.5        0.70710678] [0.5 0.5 1. ] [0.25 0.25 0.5 ]


In [16]:
data = np.array([[0, 0, 0], [1, 0, 1], [0, 1, 2], [1, 1, 1]])

((data - scaler.mean_)/scaler.var_)*scaler.scale_

array([[-1.        , -1.        , -1.41421356],
       [ 1.        , -1.        ,  0.        ],
       [-1.        ,  1.        ,  1.41421356],
       [ 1.        ,  1.        ,  0.        ]])

In [17]:
data = np.array([[0, 0, 0], [1, 0, 1], [0, 1, 2], [1, 1, 1]])

(data - scaler.mean_)/scaler.scale_

array([[-1.        , -1.        , -1.41421356],
       [ 1.        , -1.        ,  0.        ],
       [-1.        ,  1.        ,  1.41421356],
       [ 1.        ,  1.        ,  0.        ]])

In [19]:
import numpy as np
np.savetxt('scaler_mean.txt', scaler.mean_)
np.savetxt('scaler_scale.txt', scaler.scale_)

In [23]:
print(np.std(data, axis=0))
print(np.var(data, axis=0))
print(np.mean(data, axis=0))

[0.5        0.5        0.70710678]
[0.25 0.25 0.5 ]
[0.5 0.5 1. ]
